import pandas as pd
import matplotlib.pyplot as plt
'''
Name: Shankar Choudhury
Case Network ID: sxc1782
Filename: analyze_flows.py
Date created: 2025-10-28
Brief description:
  This code analyzes the NetFlow (-n) and RTT (-r) mode outputs generated by
  the router simulator. It uses pandas and matplotlib to compute summary
  statistics and visualize trends in network traffic, including protocol
  distribution, top source IPs by payload, flow duration distribution, and
  round-trip time histograms. The resulting figures help highlight global
  characteristics of the captured trace.
'''
# Load NetFlow data
nmode = pd.read_csv("nmode.txt", sep=" ", header=None,
                    names=["sip", "sport", "dip", "dport", "proto", "first_ts", "duration", "tot_pkts", "tot_bytes"])

# Load RTT data
rmode = pd.read_csv("rmode.txt", sep=" ", header=None,
                    names=["sip", "sport", "dip", "dport", "rtt"])
rmode = rmode[rmode["rtt"] != "-"]
rmode["rtt"] = rmode["rtt"].astype(float)

# NetFlow analysis
print("Total flows:", len(nmode))
print("Total packets:", nmode["tot_pkts"].sum())
print("Total payload bytes:", nmode["tot_bytes"].sum())

# Protocol mix
proto_counts = nmode["proto"].value_counts()
proto_counts.plot(kind="bar", title="Protocol Distribution (TCP vs UDP)")
plt.xlabel("Protocol")
plt.ylabel("Number of Flows")
plt.tight_layout()
plt.savefig("protocol_distribution.png")
plt.close()

# Top IPs
top_senders = nmode.groupby("sip")["tot_bytes"].sum().sort_values(ascending=False).head(10)
top_senders.plot(kind="barh", title="Top 10 Source IPs by Payload")
plt.xlabel("Total Payload Bytes")
plt.tight_layout()
plt.savefig("top_senders.png")
plt.close()

# Flow duration distribution
nmode["duration"] = nmode["duration"].astype(float)
plt.hist(nmode["duration"], bins=50)
plt.title("Flow Duration Distribution")
plt.xlabel("Duration (seconds)")
plt.ylabel("Number of Flows")
plt.tight_layout()
plt.savefig("flow_duration_hist.png")
plt.close()

# RTT analysis
plt.hist(rmode["rtt"], bins=50)
plt.title("Round Trip Time (RTT) Distribution")
plt.xlabel("RTT (seconds)")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("rtt_distribution.png")
plt.close()

print("Average RTT:", rmode["rtt"].mean())
print("Median RTT:", rmode["rtt"].median())
print("Max RTT:", rmode["rtt"].max())
